import { Navigation } from "@/components/Navigation";
import "./globals.css";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "My first Next.js app",
  description: "Generated by create next app",
  keywords: "next, react, app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
